version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: whatever[baby]
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    image: jimboeri/rwc19
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db

    environment:
      RWC_TEST_DAILY: T
      RWC_WEB_BASE_URL: http://localhost:8002

volumes:
  postgres-data:
