# Generated by Django 4.2.3 on 2023-07-30 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0002_prediction_gotwinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField(default=0, help_text='Order of round')),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwc23.team')),
            ],
            options={
                'ordering': ['Order'],
            },
        ),
    ]
