# Generated by Django 4.2.3 on 2023-07-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0003_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
