# Generated by Django 4.2.3 on 2023-07-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0004_alter_round_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='Round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='RWC23', to='rwc23.round'),
        ),
    ]
