# Generated by Django 4.2.3 on 2023-07-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0005_game_round'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['Round', 'gamedate']},
        ),
        migrations.AlterField(
            model_name='game',
            name='Round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RWC23', to='rwc23.round'),
        ),
    ]
