# Generated by Django 4.2.3 on 2023-08-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0006_alter_game_options_alter_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
