# Generated by Django 4.2.3 on 2023-08-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0008_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='Round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwc23.round'),
        ),
    ]
