# Generated by Django 4.2.4 on 2023-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0015_prediction_playerround'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='resultText',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
