# Generated by Django 4.2.4 on 2023-08-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rwc23', '0017_alter_prediction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerround',
            options={'ordering': ['round__Order']},
        ),
    ]
