# Generated by Django 6.1 on 2026-08-25 08:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamedate', models.DateTimeField(blank=True, null=True)),
                ('score1', models.PositiveIntegerField(default=0, help_text='Score of 1st team')),
                ('score2', models.PositiveIntegerField(default=0, help_text='Score of 2nd team')),
                ('finished', models.BooleanField(default=False)),
                ('high_point', models.FloatField(default=0)),
                ('average', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('result_text', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'ordering': ['round__order', 'gamedate'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('kind', models.CharField(choices=[('TOURNAMENT', 'Tournament'), ('SERIES', 'Series'), ('LEAGUE', 'League'), ('OTHER', 'Other')], default='TOURNAMENT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open for registration'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public - anyone can join'), ('INVITE', 'Invite only')], default='INVITE', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('default_entry_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('scoring_rules', models.JSONField(blank=True, help_text="GoRules ZEN Engine JDM decision graph used to score predictions once a game is finished. See swim/arena/rules/example_margin_scoring.json for a worked example reproducing the classic win-margin/draw scoring, and arena/rules.py for the facts passed in (predictedResult, actualResult, predictedSpread, actualSpread) and the required 'points' output. Predictions cannot be scored until this is set.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('PLAYER', 'Player')], default='PLAYER', max_length=10)),
                ('phone_number', models.CharField(blank=True, default='', max_length=50)),
                ('blocked', models.BooleanField(default=False)),
                ('fully_paid', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='arena.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['competition__name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rounds', to='arena.membership')),
            ],
            options={
                'ordering': ['round__order'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(choices=[(0, 'No selection'), (1, 'Team 1 wins'), (2, 'Team 2 wins'), (3, 'Draw')], default=0)),
                ('spread', models.PositiveIntegerField(default=0, help_text='Predicted winning margin')),
                ('points', models.FloatField(default=0)),
                ('override', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='arena.game')),
                ('player_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='arena.playerround')),
            ],
            options={
                'ordering': ['game__gamedate'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of round')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('finish', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('N', 'Not current'), ('C', 'Current'), ('F', 'Finished')], default='N', max_length=1)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, help_text="Overrides the competition's default entry fee if set", max_digits=6, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='arena.competition')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='playerround',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rounds', to='arena.round'),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='arena.round'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField(blank=True, default='')),
                ('pool', models.CharField(blank=True, default='', max_length=1)),
                ('code', models.CharField(blank=True, default='', max_length=3)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='arena.competition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team1', to='arena.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team2', to='arena.team'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'competition'), name='unique_membership_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.UniqueConstraint(fields=('player_round', 'game'), name='unique_prediction_per_game'),
        ),
        migrations.AddConstraint(
            model_name='playerround',
            constraint=models.UniqueConstraint(fields=('membership', 'round'), name='unique_player_round'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_team_name_per_competition'),
        ),
    ]
