# Generated by Django 2.2.5 on 2019-09-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=30)),
                ('descr', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
