# Generated by Django 2.2.5 on 2019-09-16 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamedate', models.DateTimeField(blank=True, null=True)),
                ('score1', models.IntegerField(default=0, help_text='Score of 1st teame')),
                ('score2', models.IntegerField(default=0, help_text='Score of 2nd teame')),
                ('Team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rwc19.Team')),
                ('Team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='rwc19.Team')),
            ],
        ),
    ]
