# Generated by Django 2.2.5 on 2019-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0004_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='points',
            field=models.FloatField(default=0, help_text='For and away points'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='pool',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='score1',
            field=models.IntegerField(default=0, help_text='Score of 1st team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score2',
            field=models.IntegerField(default=0, help_text='Score of 2nd team'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='score1',
            field=models.IntegerField(default=0, help_text='Score of 1st team'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='score2',
            field=models.IntegerField(default=0, help_text='Score of 2nd team'),
        ),
    ]
