# Generated by Django 2.2.5 on 2019-09-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0005_auto_20190916_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totalPoints',
            field=models.FloatField(default=0, help_text='Total For and away points'),
        ),
    ]
