# Generated by Django 2.2.5 on 2019-09-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0006_profile_totalpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediction',
            name='textname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
