# Generated by Django 2.2.5 on 2019-09-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0010_auto_20190925_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='high_point',
            field=models.FloatField(default=0),
        ),
    ]
