# Generated by Django 2.2.6 on 2019-10-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0012_prediction_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average',
            field=models.FloatField(default=0),
        ),
    ]
