# Generated by Django 2.2.6 on 2019-10-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwc19', '0013_game_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='average',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
